AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create S3 bucket for vpc flow logs'

Parameters:
  BucketNamePrefix:
    Description: 'Name of S3 bucket for vpc flow logs delivery'
    Type: String
    Default: ''

Resources:
  LogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${AWS::AccountId}-${AWS::Region}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: RetentionRule
            Status: Enabled
            ExpirationInDays: '365'
            NoncurrentVersionExpirationInDays: '365'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  LogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LogBucket

      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Deny non-HTTPS access
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: !Sub "${LogBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Action:
              - 's3:PutObject'
            Resource: !Sub "${LogBucket.Arn}/*"
            Condition:
              StringEquals:
                's3:x-amz-acl': 'bucket-owner-full-control'
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Action:
              - "s3:GetBucketAcl"
            Resource: !GetAtt "LogBucket.Arn"

Outputs:
  BucketArn:
    Description: ARN of S3 bucket for vpc flow logs delivery
    Value: !GetAtt LogBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
  BucketName:
    Description: Name of S3 bucket for vpc flow logs delivery
    Value: !Ref LogBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"