AWSTemplateFormatVersion: '2010-09-09'
Description: IPAM

Parameters:
  Region:
    Description: 'Operating regions'
    Type: String
  TopLevelCidr:
    Description: 'CIDR for Top Level Pool'
    Type: String
  RegionLevelCidr:
    Description: 'CIDR for Region Level Pool'
    Type: String
  ProdLevelCidr:
    Description: 'CIDR for Production Pool'
    Type: String
  ProdOuArn:
    Description: 'Prod OU ARN'
    Type: String

Resources:
  IPAM:
    Type: AWS::EC2::IPAM
    Properties:
      OperatingRegions:
        - RegionName: !Sub "${Region}"

  topLevelPool:
    Type: AWS::EC2::IPAMPool
    Properties:
      AddressFamily: ipv4
      IpamScopeId: !GetAtt IPAM.PrivateDefaultScopeId
      ProvisionedCidrs:
        - Cidr: !Sub "${TopLevelCidr}"

  regionLevelPool:
    Type: AWS::EC2::IPAMPool
    Properties:
      AddressFamily: ipv4
      IpamScopeId: !GetAtt IPAM.PrivateDefaultScopeId
      ProvisionedCidrs:
        - Cidr: !Sub "${RegionLevelCidr}"
      SourceIpamPoolId: !GetAtt topLevelPool.IpamPoolId
      Tags:
        - Key: "Name"
          Value: !Sub "${Region}-Level-Pool"

  ProdLevelPool:
    Type: AWS::EC2::IPAMPool
    Properties:
      AddressFamily: ipv4
      IpamScopeId: !GetAtt IPAM.PrivateDefaultScopeId
      AllocationMaxNetmaskLength: 28
      AllocationMinNetmaskLength: 16
      ProvisionedCidrs:
        - Cidr: !Sub "${ProdLevelCidr}"
      SourceIpamPoolId: !GetAtt regionLevelPool.IpamPoolId
      Locale: !Sub "${Region}"
      AutoImport: True
      Tags:
        - Key: "Name"
          Value: "Production"

  ProdPoolShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: IPAM-Prod-pool-share
      ResourceArns:
        - !GetAtt ProdLevelPool.Arn
      Principals:
        - !Sub "${ProdOuArn}"

Outputs:
  ProdPoolID:
    Description: Prod Pool ID
    Value: !GetAtt ProdLevelPool.IpamPoolId
    Export:
      Name: IPAM-Prod-PoolID