AWSTemplateFormatVersion: '2010-09-09'
Description: Creates simple demo VPC

Parameters:
  IMAPPoolID:
    Type: String
    Default: ''
  VpcCidrSize:
    Type: Number
    Default: 16
  ExternalLogBucket:
    Description: '(Optional) Name of an S3 bucket where you want to store flow logs. If you leave this empty, FlowLogs will not be configured'
    Type: String
    Default: ''
  TrafficType:
    Description: 'The type of traffic to log.'
    Type: String
    Default: ALL
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL

### VPC ###
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Ipv4IpamPoolId: !Ref IMAPPoolID
      Ipv4NetmaskLength: !Ref VpcCidrSize

### VPC Flow Logs ###
  FlowLogExternalBucket:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      LogDestination: !Sub 'arn:aws:s3:::${ExternalLogBucket}'
      LogDestinationType: s3
      ResourceId: !Ref VPC
      ResourceType: 'VPC'
      TrafficType: !Ref TrafficType